	SET LANGUAGE spanish;
	SELECT 
				ISNULL(EXPE.CCODEXPCLI, '') AS CCODEXPCLI, 
				FIA.CCODCTACRE, CNROCARFIA, GEN.CCODCLIENTE AS CCODCLISOL
				, CLITIT.CNOMCLIENTE AS CNOMCLISOL
				--Representantes 
				,CodigoRepresentante = isnull(RL.cCodCliRep,'NO REGISTRA')
				,DocumentoRepresentante = ISNULL(isnull(CC.cNroDocIde,CC.cNroDocTri),'NO REGISTRA')
				,NombreRepresentante = ISNULL(CC.cNomCliente,'NO REGISTRA')				
				--Accionistas
				,DocAccionista = ISNULL(AC.cDocIdeAcc,'NO REGISTRA')
				,NombreAccinosta = isnull(AC.cApeNomAcc,'NO REGISTRA')
				,PorcentAcciones = isnull(AC.cPorParAcc,'NO REGISTRA')
				-------------------------
				,FIA.CCODCLIENTE AS CCODCLIFAV, CLIFAV.CNOMCLIENTE AS CNOMCLIFAV
				,MON.CDESCORTA AS CTIPMONFIA, MON.CDESTIPMON, NVALCARFIA
				, DFECINIFIA = left(cast(FIA.DFECINIFIA as date),10)
				,FecIniCFAnio=YEAR(FIA.DFECINIFIA)
				,FecIniCFMes=DATENAME(MONTH,FIA.DFECINIFIA) 
				, DFECCANFIA = left(cast(FIA.DFECCANFIA as date),10)
				,FIA.NPLAOTOFIA, MODCF.CDESMODFIA
				--ISNULL(TIPOGAR.CCODGARCLI, '') AS CCODGARCLI
				--, ISNULL(TIPOGAR.CCODCUENTA, '') AS CCODCUENTA
				--,ISNULL(TIPOGAR.CDESTIPGAR, '') AS CDESTIPGAR
				--,ISNULL(TIPOGAR.CTIPMONGAR, '') AS CTIPMONGAR
				--,ISNULL(TIPOGAR.NMONGARORI, 0.00) AS NMONGARORI
				--, S.cCodOficin
				,O.cDesOficin--,ZON.nCodZona
				,ZON.cDesZona
				--,CLITIT.cCodCiiu
				--,B.ccodciiu, B.cdesactivi
				--,CLITIT.cCodCiuDet
				,C.ccodciudet ,c.cdesactivi
			FROM KPYMCRECARFIA FIA (NOLOCK)
				inner JOIN GENMCRECLI GEN (NOLOCK) 
					ON(FIA.CCODCTACRE = GEN.CCODCTACRE)
				LEFT JOIN KPYTMODCARFIA MODCF (NOLOCK) 
					ON(FIA.cCodModFia = MODCF.cCodModFia)
				inner JOIN CMACHYOCLI_MANIANA.DBO.CLIMClienteS CLITIT (NOLOCK) 						
					ON(CLITIT.CCODCLIENTE = GEN.CCODCLIENTE)
				LEFT JOIN CMACHYOCLI_MANIANA.DBO.CLIDExpediente EXPE (NOLOCK) 
					ON(EXPE.CCODCLIENT = CLITIT.CCODCLIENTE AND EXPE.CTIPEXPCLI = 'K'
						AND EXPE.LCONESTADO = 1) 
				inner JOIN CMACHYOCLI_MANIANA.DBO.CLIMClienteS CLIFAV (NOLOCK) 
					ON(CLIFAV.CCODCLIENTE = FIA.CCODCLIENTE)
				/*
				inner JOIN 
					(
					SELECT CLIMGAR.CCODGARCLI, CLIMGAR.CCODCUENTA, GARLIN.CCODLINCRE, TIPGAR.CDESTIPGAR, MON.CDESCORTA AS CTIPMONGAR, NMONGARORI
					 FROM KPYDGARLINCRE GARLIN (NOLOCK) 
						INNER JOIN CMACHYOCLI_MANIANA.DBO.CLIMGarCliente CLIMGAR (NOLOCK) 
							ON(CLIMGAR.CCODGARCLI = GARLIN.CCODGARCLI AND CLIMGAR.CCODCLIENTE = GARLIN.CCODCLIENTE
								AND CLIMGAR.CCODESTGAR = 'A' AND GARLIN.CCODESTGAR = 'A')
						LEFT JOIN GENDGARANTIA TIPGAR (NOLOCK)
							ON(TIPGAR.CCODgarant = CLIMGAR.CCODTIPGAR)
						LEFT JOIN GENTMONEDA MON (NOLOCK) 
							ON(MON.CCODTIPMON = CLIMGAR.CCODTIPMON)
					) AS TIPOGAR
					ON(TIPOGAR.CCODLINCRE = GEN.CCODLINCRE )
				*/
				LEFT JOIN GENTMONEDA MON (NOLOCK) 
					ON(MON.CCODTIPMON  = FIA.CCODTIPMON)
				
				left JOIN KPYMSolicitud S
					ON FIA.cCodSolCre = S.cCodSolCre 
			
				INNER JOIN GENTOficinas O
					on O.cCodOficin = S.cCodOficin
				INNER JOIN [Gentofizonas] GOZ
					ON GOZ.cCodOficin = O.cCodOficin and GOZ.lEstZonOfi = '1'
				INNER JOIN [GentZonas] ZON
					ON ZON.nCodZona = GOZ.nCodZona
				
				inner join GENTCodCiiu B
					on CLITIT.cCodCiiu = B.ccodciiu	
				inner join GENDCodCiiu C
					on C.ccodciudet = CLITIT.cCodCiuDet	
					
				--Representantes				
				left join CMACHYOCLI_MANIANA.DBO.CLIDRepresCli RL
					on RL.cCodCliente = GEN.CCODCLIENTE
				left join CMACHYOCLI_MANIANA.DBO.ClimClientes CC
					on CC.cCodCliente = RL.cCodCliRep														

				--Accionistas
				left join CMACHYOCLI_MANIANA.DBO.clidactaccjur AC
					on AC.cCodCliente = GEN.CCODCLIENTE

			WHERE CESTCARFIA = 'K'
			ORDER BY FIA.CCODTIPMON, FIA.CNROCARFIA