	--sp_helptext KPY_REPCARFIA_SP

			/***********************************************************************************************************************************************************************************************
		*	Objetivo: Reporte de Cartas Fianza

		*	Escrito por: 			isaave
		*	Email/Movil/Phone:		isaavedra@CMAC-HUANCAYO.COM.PE
		*	Fecha creación: 2003-06-30
		*	Sistema / Modulo:	VITALIS / CREDITOS
		*	Modificaciones:    
		*		Fecha  		Responsable		Descripcion del cambio
		*		2005/10/21	GLOPEZ			Se cambia a la tabla GENDGarantia
		*		2010.01.28	AROBLE			Se adiciona el codigo de oficina para mejor filtro
		*	Sintaxis de ejemplo:  

			EXEC KPY_REPCARFIA_SP  
				@x_dFecIni = '2005-04-01',  
				@x_dFecFin = '2005-10-30',  
				@x_cOpcion = '2'
***********************************************************************************************************************************************************************************************/  

		CREATE PROCEDURE KPY_REPCARFIA_SP
			@x_dFecIni datetime,  
			@x_dFecFin datetime,
			@x_cCodOfi VARCHAR(3),
			@x_cOpcion CHAR(1) = '1'	 
		AS   

		SET NOCOUNT ON  
		SET DATEFORMAT YMD  

		IF @x_cOpcion = '1'
		BEGIN
			--=========================================================================
			-- CARTAS FIANZAS VIGENTES A LA FECHA 
			--=========================================================================
			SELECT 
				ISNULL(EXPE.CCODEXPCLI, '') AS CCODEXPCLI, 
				FIA.CCODCTACRE, CNROCARFIA, GEN.CCODCLIENTE AS CCODCLISOL, CLITIT.CNOMCLIENTE AS CNOMCLISOL,
				FIA.CCODCLIENTE AS CCODCLIFAV, CLIFAV.CNOMCLIENTE AS CNOMCLIFAV, 
				MON.CDESCORTA AS CTIPMONFIA, MON.CDESTIPMON, NVALCARFIA, FIA.DFECINIFIA, FIA.DFECCANFIA, 
				FIA.NPLAOTOFIA, MOD.CDESMODFIA,
				ISNULL(TIPOGAR.CCODGARCLI, '') AS CCODGARCLI, ISNULL(TIPOGAR.CCODCUENTA, '') AS CCODCUENTA, 
				ISNULL(TIPOGAR.CDESTIPGAR, '') AS CDESTIPGAR, 
				ISNULL(TIPOGAR.CTIPMONGAR, '') AS CTIPMONGAR, ISNULL(TIPOGAR.NMONGARORI, 0.00) AS NMONGARORI
			FROM KPYMCRECARFIA FIA (NOLOCK)
				INNER JOIN GENMCRECLI GEN (NOLOCK) 
					ON(FIA.CCODCTACRE = GEN.CCODCTACRE)
				LEFT JOIN KPYTMODCARFIA MOD (NOLOCK) 
					ON(FIA.cCodModFia = MOD.cCodModFia)
				INNER JOIN CMACHYOCLI_MANIANA.DBO.CLIMClienteS CLITIT (NOLOCK) 
					ON(CLITIT.CCODCLIENTE = GEN.CCODCLIENTE)
				LEFT JOIN CMACHYOCLI_MANIANA.DBO.CLIDExpediente EXPE (NOLOCK) 
					ON(EXPE.CCODCLIENT = CLITIT.CCODCLIENTE AND EXPE.CTIPEXPCLI = 'K' AND EXPE.LCONESTADO = 1) 
				INNER JOIN CMACHYOCLI_MANIANA.DBO.CLIMClienteS CLIFAV (NOLOCK) 
					ON(CLIFAV.CCODCLIENTE = FIA.CCODCLIENTE)
				LEFT JOIN 
					(SELECT CLIMGAR.CCODGARCLI, CLIMGAR.CCODCUENTA, GARLIN.CCODLINCRE, TIPGAR.CDESTIPGAR, MON.CDESCORTA AS CTIPMONGAR, NMONGARORI
					 FROM KPYDGARLINCRE GARLIN (NOLOCK) 
						INNER JOIN CMACHYOCLI_MANIANA.DBO.CLIMGarCliente CLIMGAR (NOLOCK) 
							ON(CLIMGAR.CCODGARCLI = GARLIN.CCODGARCLI AND CLIMGAR.CCODCLIENTE = GARLIN.CCODCLIENTE
								AND CLIMGAR.CCODESTGAR = 'A' AND GARLIN.CCODESTGAR = 'A')
						LEFT JOIN GENDGARANTIA TIPGAR (NOLOCK)
							ON(TIPGAR.CCODgarant = CLIMGAR.CCODTIPGAR)
						LEFT JOIN GENTMONEDA MON (NOLOCK) 
							ON(MON.CCODTIPMON = CLIMGAR.CCODTIPMON)
					) AS TIPOGAR
					ON(TIPOGAR.CCODLINCRE = GEN.CCODLINCRE )
				LEFT JOIN GENTMONEDA MON (NOLOCK) 
					ON(MON.CCODTIPMON  = FIA.CCODTIPMON)
				INNER JOIN KPYMSolicitud S
					ON FIA.cCodSolCre = S.cCodSolCre 
			WHERE S.cCodOficin like @x_cCodOfi
				AND CESTCARFIA = 'K'
			ORDER BY FIA.CCODTIPMON, FIA.CNROCARFIA

		END

		IF @x_cOpcion = '2'
		BEGIN
			--=========================================================================
			-- CARTAS FIANZAS OTORGADAS EN EL RANGO DE FECHAS
			--=========================================================================
			SELECT 
				ISNULL(EXPE.CCODEXPCLI, '') AS CCODEXPCLI, 
				FIA.CCODCTACRE, CNROCARFIA, GEN.CCODCLIENTE AS CCODCLISOL, CLITIT.CNOMCLIENTE AS CNOMCLISOL,
				FIA.CCODCLIENTE AS CCODCLIFAV, CLIFAV.CNOMCLIENTE AS CNOMCLIFAV, 
				MON.CDESCORTA AS CTIPMONFIA, MON.CDESTIPMON, NVALCARFIA, FIA.DFECINIFIA, FIA.DFECCANFIA, 
				FIA.NPLAOTOFIA, MOD.CDESMODFIA,
				ISNULL(TIPOGAR.CCODGARCLI, '') AS CCODGARCLI, ISNULL(TIPOGAR.CCODCUENTA, '') AS CCODCUENTA, 
				ISNULL(TIPOGAR.CDESTIPGAR, '') AS CDESTIPGAR, 
				ISNULL(TIPOGAR.CTIPMONGAR, '') AS CTIPMONGAR, ISNULL(TIPOGAR.NMONGARORI, 0.00) AS NMONGARORI
			FROM GENMKARDEX KAR (NOLOCK)
				INNER JOIN KPYMCRECARFIA FIA (NOLOCK) 		
					ON(FIA.CCODCTACRE = KAR.CCODCUENTA 
						AND KAR.CCODTIPKAR = 'FIA' AND KAR.CCODESTTRX = 'N')
				INNER JOIN GENMCRECLI GEN (NOLOCK) 
					ON(FIA.CCODCTACRE = GEN.CCODCTACRE)
				LEFT JOIN KPYTMODCARFIA MOD (NOLOCK)
					ON(FIA.cCodModFia = MOD.cCodModFia)
				INNER JOIN CMACHYOCLI_MANIANA.DBO.CLIMClienteS CLITIT (NOLOCK) 
					ON(CLITIT.CCODCLIENTE = GEN.CCODCLIENTE)
				LEFT JOIN CMACHYOCLI_MANIANA.DBO.CLIDExpediente EXPE (NOLOCK) 
					ON(EXPE.CCODCLIENT = CLITIT.CCODCLIENTE AND EXPE.CTIPEXPCLI = 'K' AND EXPE.LCONESTADO = 1) 
				INNER JOIN CMACHYOCLI_MANIANA.DBO.CLIMClienteS CLIFAV (NOLOCK) 
					ON(CLIFAV.CCODCLIENTE = FIA.CCODCLIENTE)
				LEFT JOIN 
					(SELECT CLIMGAR.CCODGARCLI, CLIMGAR.CCODCUENTA, GARLIN.CCODLINCRE, TIPGAR.CDESTIPGAR, MON.CDESCORTA AS CTIPMONGAR, NMONGARORI
					 FROM KPYDGARLINCRE GARLIN (NOLOCK) 
						INNER JOIN CMACHYOCLI_MANIANA.DBO.CLIMGarCliente CLIMGAR (NOLOCK)
							ON(CLIMGAR.CCODGARCLI = GARLIN.CCODGARCLI AND CLIMGAR.CCODCLIENTE = GARLIN.CCODCLIENTE
								AND CLIMGAR.CCODESTGAR = 'A' AND GARLIN.CCODESTGAR = 'A')
						LEFT JOIN GENDGarantia TIPGAR (NOLOCK)
							ON(TIPGAR.CCODGarant = CLIMGAR.CCODTIPGAR)
						LEFT JOIN GENTMONEDA MON (NOLOCK)
							ON(MON.CCODTIPMON = CLIMGAR.CCODTIPMON)
					) AS TIPOGAR
					ON(TIPOGAR.CCODLINCRE = GEN.CCODLINCRE )
				LEFT JOIN GENTMONEDA MON (NOLOCK) 
					ON(MON.CCODTIPMON  = FIA.CCODTIPMON)
				INNER JOIN KPYMSolicitud S
					ON FIA.cCodSolCre = S.cCodSolCre 			
			WHERE S.cCodOficin like @x_cCodOfi 
				AND CESTCARFIA = 'K' 
				and DFECINIFIA BETWEEN @x_dFecIni AND @x_dFecFin  
				AND KAR.CCODTIPOPE = '1023'  
				AND KAR.DFECKARDEX BETWEEN @x_dFecIni AND @x_dFecFin  
			ORDER BY FIA.CCODTIPMON, FIA.CNROCARFIA
		END

		IF @x_cOpcion = '3'
		BEGIN
			--=========================================================================
			-- CARTAS FIANZAS CANCELADOS
			--=========================================================================
			SELECT 
				ISNULL(EXPE.CCODEXPCLI, '') AS CCODEXPCLI, 
				FIA.CCODCTACRE, CNROCARFIA, GEN.CCODCLIENTE AS CCODCLISOL, CLITIT.CNOMCLIENTE AS CNOMCLISOL,
				FIA.CCODCLIENTE AS CCODCLIFAV, CLIFAV.CNOMCLIENTE AS CNOMCLIFAV, 
				MON.CDESCORTA AS CTIPMONFIA, MON.CDESTIPMON, NVALCARFIA, FIA.DFECINIFIA, FIA.DFECCANFIA, 
				FIA.NPLAOTOFIA, MOD.CDESMODFIA,
				ISNULL(TIPOGAR.CCODGARCLI, '') AS CCODGARCLI, ISNULL(TIPOGAR.CCODCUENTA, '') AS CCODCUENTA,
				ISNULL(TIPOGAR.CDESTIPGAR, '') AS CDESTIPGAR, 
				ISNULL(TIPOGAR.CTIPMONGAR, '') AS CTIPMONGAR, ISNULL(TIPOGAR.NMONGARORI, 0.00) AS NMONGARORI
			FROM GENMKARDEX KAR (NOLOCK)
				INNER JOIN KPYMCRECARFIA FIA (NOLOCK)		
					ON(FIA.CCODCTACRE = KAR.CCODCUENTA 
						AND KAR.CCODTIPKAR = 'FIA' AND KAR.CCODESTTRX = 'N')
				INNER JOIN GENMCRECLI GEN (NOLOCK) 
					ON(FIA.CCODCTACRE = GEN.CCODCTACRE)
				LEFT JOIN KPYTMODCARFIA MOD (NOLOCK)
					ON(FIA.cCodModFia = MOD.cCodModFia)
				INNER JOIN CMACHYOCLI_MANIANA.DBO.CLIMClienteS CLITIT (NOLOCK) 
					ON(CLITIT.CCODCLIENTE = GEN.CCODCLIENTE)
				LEFT JOIN CMACHYOCLI_MANIANA.DBO.CLIDExpediente EXPE (NOLOCK) 
					ON(EXPE.CCODCLIENT = CLITIT.CCODCLIENTE AND EXPE.CTIPEXPCLI = 'K' AND EXPE.LCONESTADO = 1) 
				INNER JOIN CMACHYOCLI_MANIANA.DBO.CLIMClienteS CLIFAV (NOLOCK)
					ON(CLIFAV.CCODCLIENTE = FIA.CCODCLIENTE)
				LEFT JOIN 
					(SELECT CLIMGAR.CCODGARCLI, CLIMGAR.CCODCUENTA, GARLIN.CCODLINCRE, TIPGAR.CDESTIPGAR, MON.CDESCORTA AS CTIPMONGAR, NMONGARORI
					FROM KPYDGARLINCRE GARLIN (NOLOCK) 
						INNER JOIN CMACHYOCLI_MANIANA.DBO.CLIMGarCliente CLIMGAR (NOLOCK)
							ON(CLIMGAR.CCODGARCLI = GARLIN.CCODGARCLI AND CLIMGAR.CCODCLIENTE = GARLIN.CCODCLIENTE
								AND CLIMGAR.CCODESTGAR = 'A' AND GARLIN.CCODESTGAR = 'A')
						LEFT JOIN GENDGarantia TIPGAR (NOLOCK)
							ON(TIPGAR.CCODgarant = CLIMGAR.CCODTIPGAR)
						LEFT JOIN GENTMONEDA MON (NOLOCK)
							ON(MON.CCODTIPMON = CLIMGAR.CCODTIPMON)
					) AS TIPOGAR
					ON(TIPOGAR.CCODLINCRE = GEN.CCODLINCRE )
				LEFT JOIN GENTMONEDA MON 
					ON(MON.CCODTIPMON  = FIA.CCODTIPMON)
				INNER JOIN KPYMSolicitud S
					ON FIA.cCodSolCre = S.cCodSolCre 			
			WHERE S.cCodOficin like @x_cCodOfi 		
				AND KAR.CCODTIPOPE = '1400'  
				AND KAR.DFECKARDEX BETWEEN @x_dFecIni AND @x_dFecFin  
			ORDER BY FIA.CCODTIPMON, FIA.CNROCARFIA
		END

		IF @x_cOpcion = '4'
		BEGIN
			--=========================================================================
			-- COBRO DE COMISIONES DE CARTAS FIANZAS EN EL RANGO DE FECHAS
			--=========================================================================
			SELECT 
				ISNULL(EXPE.CCODEXPCLI, '') AS CCODEXPCLI, 
				FIA.CCODCTACRE, CNROCARFIA, GEN.CCODCLIENTE AS CCODCLISOL, CLITIT.CNOMCLIENTE AS CNOMCLISOL,
				FIA.CCODCLIENTE AS CCODCLIFAV, CLIFAV.CNOMCLIENTE AS CNOMCLIFAV, 
				MON.CDESCORTA AS CTIPMONFIA, MON.CDESTIPMON, NVALCARFIA, FIA.DFECINIFIA, FIA.DFECCANFIA, 
				FIA.NPLAOTOFIA, MOD.CDESMODFIA,
				ISNULL(TIPOGAR.CCODGARCLI, '') AS CCODGARCLI, ISNULL(TIPOGAR.CCODCUENTA, '') AS CCODCUENTA, 
				ISNULL(TIPOGAR.CDESTIPGAR, '') AS CDESTIPGAR, 
				ISNULL(TIPOGAR.CTIPMONGAR, '') AS CTIPMONGAR, ISNULL(TIPOGAR.NMONGARORI, 0.00) AS NMONGARORI,
				KAR.NMONTOTKAR
			FROM GENMKARDEX KAR (NOLOCK)
				INNER JOIN KPYMCRECARFIA FIA (NOLOCK)		
					ON(FIA.CCODCTACRE = KAR.CCODCUENTA 
						AND KAR.CCODTIPKAR = 'FIA' AND KAR.CCODESTTRX = 'N')
				INNER JOIN GENMCRECLI GEN (NOLOCK) 
					ON(FIA.CCODCTACRE = GEN.CCODCTACRE)
				LEFT JOIN KPYTMODCARFIA MOD (NOLOCK) 
					ON(FIA.cCodModFia = MOD.cCodModFia)
				INNER JOIN CMACHYOCLI_MANIANA.DBO.CLIMClienteS CLITIT (NOLOCK) 
					ON(CLITIT.CCODCLIENTE = GEN.CCODCLIENTE)
				LEFT JOIN CMACHYOCLI_MANIANA.DBO.CLIDExpediente EXPE (NOLOCK) 
					ON(EXPE.CCODCLIENT = CLITIT.CCODCLIENTE AND EXPE.CTIPEXPCLI = 'K' AND EXPE.LCONESTADO = 1) 
				INNER JOIN CMACHYOCLI_MANIANA.DBO.CLIMClienteS CLIFAV (NOLOCK) 
					ON(CLIFAV.CCODCLIENTE = FIA.CCODCLIENTE)
				LEFT JOIN 
					(SELECT 
						CLIMGAR.CCODGARCLI, CLIMGAR.CCODCUENTA, GARLIN.CCODLINCRE, TIPGAR.CDESTIPGAR, 
						MON.CDESCORTA AS CTIPMONGAR, NMONGARORI
					FROM KPYDGARLINCRE GARLIN (NOLOCK) 
						INNER JOIN CMACHYOCLI_MANIANA.DBO.CLIMGarCliente CLIMGAR (NOLOCK)
							ON(CLIMGAR.CCODGARCLI = GARLIN.CCODGARCLI AND CLIMGAR.CCODCLIENTE = GARLIN.CCODCLIENTE
								AND CLIMGAR.CCODESTGAR = 'A' AND GARLIN.CCODESTGAR = 'A')
						LEFT JOIN GENDGarantia TIPGAR (NOLOCK)
							ON(TIPGAR.cCodGarant = CLIMGAR.CCODTIPGAR)
						LEFT JOIN GENTMONEDA MON (NOLOCK)
							ON(MON.CCODTIPMON = CLIMGAR.CCODTIPMON)
					) AS TIPOGAR
					ON(TIPOGAR.CCODLINCRE = GEN.CCODLINCRE )
				LEFT JOIN GENTMONEDA MON 
					ON(MON.CCODTIPMON  = FIA.CCODTIPMON)
				INNER JOIN KPYMSolicitud S
					ON FIA.cCodSolCre = S.cCodSolCre 			
			WHERE S.cCodOficin like @x_cCodOfi 
				AND KAR.CCODTIPOPE = '1023' 
				AND KAR.DFECKARDEX BETWEEN @x_dFecIni AND @x_dFecFin  
			ORDER BY FIA.CCODTIPMON, FIA.CNROCARFIA
		END


