	-----------------------CLIENTES DESERTORES----------------------
	
	--*********************************INDEXANDO****************************************************
	CREATE NONCLUSTERED INDEX CLIEDESEJUN2015_CODIGO_CLIENTE_IXN ON CLIEDESEJUN2015(CODIGO_CLIENTE)		
	CREATE NONCLUSTERED INDEX CLIEDESEJUN2015_COD_SBS1_IXN ON CLIEDESEJUN2015(COD_SBS1)		
	CREATE NONCLUSTERED INDEX CLIEDESEJUN2015_CODIGO_CREDITO_IXN ON CLIEDESEJUN2015(CODIGO_CREDITO)
	--**********************************************************************************************

	--01
	SELECT *
	FROM CLIEDESEJUN2015

		SELECT *
		FROM CLIEDESEJUN2015 
		where COD_SBS1 = '0002094533'

		SELECT COD_SBS1, COUNT(COD_SBS1)
		FROM CLIEDESEJUN2015
		GROUP BY COD_SBS1
		HAVING COUNT(COD_SBS1) > 1
				AND COD_SBS1 NOT IN ('0000000001','0000000002')			

	--Alter Table CLIEDESEJUN2015
	--Add RCC_MAR2015 varchar(20),RCC_ABR2015 varchar(20),RCC_MAY2015 varchar(20)

	Select *
	From RCCCLIEDESE 
	WHERE CCODSBS = '0002094533' --'0000340944'
	ORDER BY CCODSBS			

			select COUNT(DISTINCT CCODEMP)
			from RCCCLIEDESE
			where CCODSBS = '0002094533' --'0000340944' --'0000290912'			

	--02 CANTIDAD DE ENTIDADES

			SELECT --CantEnt,Sec,*
				count(CantEnt)
			FROM CLIEDESEJUN2015
			--Order by Sec
			Where CantEnt !='null'
	
	--*****************************INDEXANDO****************************************************	
	CREATE NONCLUSTERED INDEX RCCCLIEDESE_CCODSBS_IXN ON RCCCLIEDESE(CCODSBS)		
	CREATE NONCLUSTERED INDEX RCCCLIEDESE_CCODEMP_IXN ON RCCCLIEDESE(CCODEMP)		
	--*******************************************************************************************

	------------------------------CURSOR CANTI ENT-----------------------------------------
		Declare @codsbs varchar(10) , @cali varchar(15), @nroentidades int, @deudat money
				
		Declare cCantEnt98 CURSOR FOR
			select COD_SBS1 from CLIEDESEJUN2015 where COD_SBS1 NOT IN ('0000000001','0000000002')
		OPEN cCantEnt98
		FETCH cCantEnt98 into @codsbs
		WHILE (@@FETCH_STATUS=0)
		BEGIN		
		
		  set @nroentidades = (select COUNT(DISTINCT CCODEMP)
								from RCCCLIEDESE
								where CCODSBS = @codsbs )											  			
		  
		  Update CLIEDESEJUN2015							
		  Set CantEnt = @nroentidades
		  where COD_SBS1 = @codsbs		  

		FETCH cCantEnt98 INTO @codsbs
		END
		CLOSE cCantEnt98
		DEALLOCATE cCantEnt98
	------------------------------------------------------------------------------------
		--validando la cant 
		SELECT CantEnt FROM CLIEDESEJUN2015 group by CantEnt 

		SELECT * FROM CLIEDESEJUN2015 where CantEnt = 'null'
			SELECT * FROM CLIEDESEJUN2015 where COD_SBS1 in ('0000000001','0000000002')				
		
		SELECT * FROM CLIEDESEJUN2015 where CantEnt <= 4 
										and COD_SBS1 not in ('0000000001','0000000002')

	------------------------------------------------------------------------------------
	
	--03 CALIFICACION SBS
	SELECT * FROM CALISBSCLIEDESE

	--*****************************INDEXANDO****************************************************	
	CREATE NONCLUSTERED INDEX CALISBSCLIEDESE_CCODSBS_IXN ON CALISBSCLIEDESE(CCODSBS)		
	CREATE NONCLUSTERED INDEX CALISBSCLIEDESE_CCODSBS2_IXN ON CALISBSCLIEDESE(CCODSBS2)
	CREATE NONCLUSTERED INDEX CALISBSCLIEDESE_CCODSBS3_IXN ON CALISBSCLIEDESE(CCODSBS3)
	CREATE NONCLUSTERED INDEX CALISBSCLIEDESE_CCODSBS4_IXN ON CALISBSCLIEDESE(CCODSBS4)
	CREATE NONCLUSTERED INDEX CALISBSCLIEDESE_CCODSBS5_IXN ON CALISBSCLIEDESE(CCODSBS5)
	CREATE NONCLUSTERED INDEX CALISBSCLIEDESE_CCODSBS6_IXN ON CALISBSCLIEDESE(CCODSBS6)
	CREATE NONCLUSTERED INDEX CALISBSCLIEDESE_CCODSBS7_IXN ON CALISBSCLIEDESE(CCODSBS7)
	CREATE NONCLUSTERED INDEX CALISBSCLIEDESE_CCODSBS8_IXN ON CALISBSCLIEDESE(CCODSBS8)	
	--*******************************************************************************************
		/*
		ALTER TABLE CLIEDESEJUN2015
		DROP COLUMN RCC_SET2014,RCC_OCT2014,RCC_NOV2014,RCC_DIC2014,RCC_ENE2015,RCC_FEB2015
		,RCC_MAR2015,RCC_ABR2015,RCC_MAY2015
		*/
  

		SELECT A.* 
			,RCC_SET2014=B.CCLAFIN8, RCC_OCT2014=B.CCLAFIN7,RCC_NOV2014=B.CCLAFIN6
			,RCC_DIC2014=B.CCLAFIN5,RCC_ENE2015=B.CCLAFIN4,RCC_FEB2015=B.CCLAFIN3
			,RCC_MAR2015=B.CCLAFIN2,RCC_ABR2015=B.CCLAFIN1,RCC_MAY2015=B.CCLAFIN		
		FROM [CLIEDESEJUN2015] A (NOLOCK)		
			INNER JOIN [CALISBSCLIEDESE] B 
				ON A.COD_SBS1 = B.CCODSBS
		WHERE A.CantEnt <= 4 and A.COD_SBS1 not in ('0000000001','0000000002')
				AND B.CCLAFIN = 0 AND B.CCLAFIN1 = 0 AND B.CCLAFIN2 = 0 
				AND B.CCLAFIN3 = 0 AND B.CCLAFIN4 = 0 AND B.CCLAFIN5 = 0 
				AND B.CCLAFIN6 = 0 AND B.CCLAFIN7 = 0 AND B.CCLAFIN8 = 0 
					-- (63,447 row(s) affected)
				AND RTRIM(CODIGO_CLIENTE) NOT IN (SELECT RTRIM(CODIGO_CLIENTE) FROM MDESERV01)
					-- (59,497 row(s) affected)
		ORDER BY SEC
	

		-- SELECT * FROM MDESERV01

	
		
