---- VALIDACIONES DINAMICAS PARA AMPLIACIONES.
SELECT *
INTO #CUR01
FROM GENDVALIDAOPE
WHERE cNomCamEva = 'cCodMotSol'
      AND cValCamEva = '''3'''
      
SELECT B.*
FROM #CUR01 A
      INNER JOIN GENDVALIDAOPE B -- SELECT TOP 20 * FROM GENDVALIDAOPE 
            ON A.nTipValida   = B.nTipValida
                  AND A.nNumValida = B.nNumValida
ORDER BY nTipValida,nNumValida


--PARA BUSCAR ALGUNA COINCIDENCIA DENTRO DE SSPS..
SELECT DISTINCT A.NAME
FROM SYSOBJECTS A
      INNER JOIN SYSCOMMENTS B
            ON A.ID = B.ID
WHERE A.TYPE = 'P'
      AND B.TEXT LIKE '%nTipValida%'