SELECT TOP 1 * 
FROM GENDGarantia GAR
WHERE B.cCodLinCre = '0020085650'

	SELECT *
	FROM KPYDGARLINCRE DGAR 
	WHERE DGAR.CCODLINCRE = '0020073453'--@cCodLinCre  
		AND DGAR.cCodEstGar = 'A'
		AND DGAR.cCodTipGar = 'RPHIP'

	SELECT *
	FROM GENDGarantia
	WHERE lconestado = 1
		and ccodgarant LIKE '%RPHIP%'


	SELECT *
	FROM KPYDGarLinCre
	WHERE cCodLinCre = '0020073453'

	SELECT CCODTIPCRE,CCODPRODUC,CCODSUBPRO,CCODOFICIN, *
	FROM KPYMSolicitud
	WHERE CCODSOLCRE = '0020091857'

	SELECT *
	FROM KPYTVALGARANT
	WHERE CCODTIPCRE + CCODPRODUC + CCODSUBPRO + CCODOFICIN = '030301002'
		AND cCodGarant = 'RPHIP'


	SELECT *
	FROM [HYO00402].CMACHYOCLI_MANIANA.dbo.[CLIMCLIENTES] CLIM 
	WHERE  CLIM.cCodCliente = '107011247503'