			--/*
			SELECT CLIMGAR.CCODGARCLI, CLIMGAR.CCODCUENTA, GARLIN.CCODLINCRE ,TIPGAR.CDESTIPGAR
					,MON.CDESCORTA AS CTIPMONGAR
					, NMONGARORI --= sum(NMONGARORI)
			FROM KPYDGARLINCRE GARLIN (NOLOCK) 
				INNER JOIN [hyo00402].CMACHYOCLI_MANIANA.DBO.CLIMGarCliente CLIMGAR (NOLOCK) 
					ON CLIMGAR.CCODGARCLI = GARLIN.CCODGARCLI 
						AND CLIMGAR.CCODCLIENTE = GARLIN.CCODCLIENTE
						AND CLIMGAR.CCODESTGAR = 'A' AND GARLIN.CCODESTGAR = 'A'
				left JOIN GENDGARANTIA TIPGAR (NOLOCK)
					ON TIPGAR.CCODgarant = CLIMGAR.CCODTIPGAR and TIPGAR.lconestado = 1
				left JOIN GENTMONEDA MON (NOLOCK) 
					ON(MON.CCODTIPMON = CLIMGAR.CCODTIPMON)
				inner join GENMCRECLI G
					on G.cCodCliente = CLIMGAR.CCODCLIENTE
				inner join KPYMCRECONVEN A
					on A.cCodCtaCre = G.cCodCtaCre
			where CLIMGAR.CCODCLIENTE = '107011772232'
			--Group By CLIMGAR.CCODGARCLI, CLIMGAR.CCODCUENTA, GARLIN.CCODLINCRE, TIPGAR.CDESTIPGAR
						--,MON.CDESCORTA--, NMONGARORI
			--*/
			---------------------------------------------------------------------------							
						
			-- CUENTA DE CREDITO Y GARANTIAS 	
			
				Select * from GENMCRECLI WHERE CCODCLIENTE = '107011772232' and CCODLINCRE in ('0020085732',
					'0020085736','0020094770', '0020094778')

				107002101009179940
				107002101009179435


			SELECT B.CCODLINCRE , A.nMonCapDes , A.nMonCapPag,A.nMonCapDes - A.nMonCapPag  , A.*
			FROM KPYMCRECONVEN A
				INNER JOIN GENMCRECLI B
					ON A.CCODCTACRE = B.CCODCTACRE
			WHERE B.CCODCLIENTE ='107011772232'
				--A.CESTCRECON = 'F' 
				--AND B.cCodLinCre = ''			
			---------------------------------------------------------------------------
			
			-- VINCULACIÓN DE CREDITOS Y GARANTIAS 
			Select  * 
			FROM KPYDGARLINCRE GARLIN (NOLOCK) 
			Where GARLIN.CCODCLIENTE ='107011772232' AND GARLIN.CCODESTGAR = 'A'

			Select CLIMGAR.CCODTIPGAR,CLIMGAR.CCODTIPMON,CLIMGAR.CCODGARCLI, CLIMGAR.CCODCUENTA,*
			From [hyo00402].CMACHYOCLI_MANIANA.DBO.CLIMGarCliente CLIMGAR (NOLOCK) 
			Where CLIMGAR.CCODCLIENTE ='107011772232' AND CLIMGAR.CCODESTGAR = 'A'

			Select --top 5
				* 
			From GENDGARANTIA TIPGAR (NOLOCK)
			where TIPGAR.CCODgarant  ='RPDCF' and TIPGAR.lconestado = 1

			Select *
			from GENTMONEDA MON (NOLOCK) 
			where MON.CCODTIPMON = '1'