
	/*
	SELECT  *
	FROM kpydComaprCre
	WHERE cCodSolCre = '0340020616' 
						
	*/

	/*
	Informar sobre el nivel de aprobación y el código de usuario que aprobó la carta fianza
	del cliente: CONSTRUCTORA AVANZA PERU SAC. (Crédito: 107034101001564901) 
	por el monto de S/. 281,594.82 Nuevos Soles. 
	*/

			SELECT 
				AP.cCodPerson, AP.lEstOpiFav, AP.lEstOpiDes, AP.cCodTipAct
				,AP.cCodUsuReg, AP.dFecRegApr
				,CCODEXPCLI = ISNULL(EXPE.CCODEXPCLI, '') 
				, (FIA.CCODCTACRE), CNROCARFIA, GEN.CCODCLIENTE AS CCODCLISOL
				, CLITIT.CNOMCLIENTE AS CNOMCLISOL,
				FIA.CCODCLIENTE AS CCODCLIFAV, CLIFAV.CNOMCLIENTE AS CNOMCLIFAV, 
				MON.CDESCORTA AS CTIPMONFIA, MON.CDESTIPMON, NVALCARFIA
				, DFECINIFIA = left(cast(FIA.DFECINIFIA as date),10)
				, DFECCANFIA = left(cast(FIA.DFECCANFIA as date),10), 
				FIA.NPLAOTOFIA, MODCF.CDESMODFIA,
				ISNULL(TIPOGAR.CCODGARCLI, '') AS CCODGARCLI
				--, ISNULL(TIPOGAR.CCODCUENTA, '') AS CCODCUENTA
				,ISNULL(TIPOGAR.CDESTIPGAR, '') AS CDESTIPGAR, 
				ISNULL(TIPOGAR.CTIPMONGAR, '') AS CTIPMONGAR
				, ISNULL(TIPOGAR.NMONGARORI, 0.00) AS NMONGARORI
				, S.cCodOficin, O.cDesOficin,ZON.nCodZona, ZON.cDesZona
				--,CLITIT.cCodCiiu
				--,B.ccodciiu, B.cdesactivi
				--,CLITIT.cCodCiuDet
				--,C.ccodciudet ,c.cdesactivi
				,FIA.cCodSolCre
			FROM KPYMCRECARFIA FIA (NOLOCK)
				INNER JOIN GENMCRECLI GEN (NOLOCK) 
					ON(FIA.CCODCTACRE = GEN.CCODCTACRE)
				LEFT JOIN KPYTMODCARFIA MODCF (NOLOCK) 
					ON(FIA.cCodModFia = MODCF.cCodModFia)
				INNER JOIN CMACHYOCLI_MANIANA.DBO.CLIMClienteS CLITIT (NOLOCK) 						
					ON(CLITIT.CCODCLIENTE = GEN.CCODCLIENTE)
				LEFT JOIN CMACHYOCLI_MANIANA.DBO.CLIDExpediente EXPE (NOLOCK) 
					ON(EXPE.CCODCLIENT = CLITIT.CCODCLIENTE AND EXPE.CTIPEXPCLI = 'K' AND EXPE.LCONESTADO = 1) 
				INNER JOIN CMACHYOCLI_MANIANA.DBO.CLIMClienteS CLIFAV (NOLOCK) 
					ON(CLIFAV.CCODCLIENTE = FIA.CCODCLIENTE)
				LEFT JOIN 
					(SELECT CLIMGAR.CCODGARCLI, CLIMGAR.CCODCUENTA, GARLIN.CCODLINCRE, TIPGAR.CDESTIPGAR, MON.CDESCORTA AS CTIPMONGAR, NMONGARORI
					 FROM KPYDGARLINCRE GARLIN (NOLOCK) 
						INNER JOIN CMACHYOCLI_MANIANA.DBO.CLIMGarCliente CLIMGAR (NOLOCK) 
							ON(CLIMGAR.CCODGARCLI = GARLIN.CCODGARCLI AND CLIMGAR.CCODCLIENTE = GARLIN.CCODCLIENTE
								AND CLIMGAR.CCODESTGAR = 'A' AND GARLIN.CCODESTGAR = 'A')
						LEFT JOIN GENDGARANTIA TIPGAR (NOLOCK)
							ON(TIPGAR.CCODgarant = CLIMGAR.CCODTIPGAR)
						LEFT JOIN GENTMONEDA MON (NOLOCK) 
							ON(MON.CCODTIPMON = CLIMGAR.CCODTIPMON)
					) AS TIPOGAR
					ON(TIPOGAR.CCODLINCRE = GEN.CCODLINCRE )
				LEFT JOIN GENTMONEDA MON (NOLOCK) 
					ON(MON.CCODTIPMON  = FIA.CCODTIPMON)
				LEFT JOIN KPYMSolicitud S
					ON FIA.cCodSolCre = S.cCodSolCre 
				INNER JOIN GENTOficinas O
					on O.cCodOficin = S.cCodOficin
				INNER JOIN [Gentofizonas] GOZ
					ON GOZ.cCodOficin = O.cCodOficin and GOZ.lEstZonOfi = '1'
				INNER JOIN [GentZonas] ZON
					ON ZON.nCodZona = GOZ.nCodZona
				--left join GENTCodCiiu B
					--on CLITIT.cCodCiiu = B.ccodciiu	
				--left join GENDCodCiiu C
					--on C.ccodciudet = CLITIT.cCodCiuDet					
				LEFT JOIN kpydComaprCre AP
					ON AP.cCodSolCre = S.cCodSolCre 
			WHERE CESTCARFIA = 'K'
				 and FIA.CCODCTACRE = '107034101001564901'
			ORDER BY FIA.CCODTIPMON, FIA.CNROCARFIA
