select * from zonacentro

SELECT * into #TMP_newage FROM  (
select 
	A.*	
from LIMASUR A 
	inner join AGWANCHAQV01 B
		on A.CODIGO_CLIENTE = B.CODIGO_CLIENTE
) as tmp

Drop table #TMP_newage

SELECT * FROM #TMP_newage 
Select * from AGWANCHAQV01

/*
RCC_SET2014	RCC_SET2014	RCC_SET2014	RCC_SET2014	RCC_SET2014	RCC_SET2014
*/
/*
UPDATE #TMP_newage
SET RCC_SET2014 = 'NORMAL'
WHERE RCC_SET2014 = '0'

UPDATE #TMP_newage
SET RCC_SET2014 = 'CPP'
WHERE RCC_SET2014 = '1'

UPDATE #TMP_newage
SET RCC_SET2014 = 'DEFICIENTE'
WHERE RCC_SET2014 = '2'

UPDATE #TMP_newage
SET RCC_SET2014 = 'DUDOSO'
WHERE RCC_SET2014 = '3'

UPDATE #TMP_newage
SET RCC_SET2014 = 'PERDIDA'
WHERE RCC_SET2014 = '4'

UPDATE #TMP_newage
SET RCC_SET2014 = 'SIN REGISTRO'
WHERE RCC_SET2014 IS NULL 

UPDATE #TMP_newage
SET Direccion_Referencia_Cliente = ''
WHERE Direccion_Referencia_Cliente IS NULL
*/

SELECT * FROM #TMP_newage 

SELECT * FROM #TMP_newage 
WHERE (RCC_FEB2015 = 'NORMAL' OR RCC_FEB2015 = 'SIN REGISTRO') 
		AND (RCC_ENE2015 = 'NORMAL' OR RCC_ENE2015 = 'SIN REGISTRO') 
		AND (RCC_DIC2014 = 'NORMAL' OR RCC_DIC2014 = 'SIN REGISTRO')
		AND (RCC_NOV2014 = 'NORMAL' OR RCC_NOV2014 = 'SIN REGISTRO')
		AND (RCC_OCT2014 = 'NORMAL' OR RCC_OCT2014 = 'SIN REGISTRO')
		AND (RCC_SET2014 = 'NORMAL' OR RCC_SET2014 = 'SIN REGISTRO')
		-- 

	SELECT * FROM #TMP_newage WHERE CODIGO_CLIENTE NOT IN 
		(SELECT CODIGO_CLIENTE FROM #TMP_newage 
		WHERE (RCC_FEB2015 = 'NORMAL' OR RCC_FEB2015 = 'SIN REGISTRO') 
		AND (RCC_ENE2015 = 'NORMAL' OR RCC_ENE2015 = 'SIN REGISTRO') 
		AND (RCC_DIC2014 = 'NORMAL' OR RCC_DIC2014 = 'SIN REGISTRO')
		AND (RCC_NOV2014 = 'NORMAL' OR RCC_NOV2014 = 'SIN REGISTRO')
		AND (RCC_OCT2014 = 'NORMAL' OR RCC_OCT2014 = 'SIN REGISTRO')
		AND (RCC_SET2014 = 'NORMAL' OR RCC_SET2014 = 'SIN REGISTRO')		
		)
		-- 
/*
SELECT * into #tmp_normal FROM  (
		SELECT CODIGO_CLIENTE FROM AGTARMAV02 
		WHERE (RCC_SET2014 = 'NORMAL' OR RCC_SET2014 = 'SIN REGISTRO') 
			AND (RCC_SET2014 = 'NORMAL' OR RCC_SET2014 = 'SIN REGISTRO') 
			AND (RCC_SET2014 = 'NORMAL' OR RCC_SET2014 = 'SIN REGISTRO')
			AND (RCC_SET2014 = 'NORMAL' OR RCC_SET2014 = 'SIN REGISTRO')
			AND (RCC_SET2014 = 'NORMAL' OR RCC_SET2014 = 'SIN REGISTRO')
			AND (RCC_SET2014 = 'NORMAL' OR RCC_SET2014 = 'SIN REGISTRO')
		) as tmp99

	SELECT CODIGO_CLIENTE FROM #tmp_normal
	
SELECT * into #tmp_roche FROM  (
		SELECT CODIGO_CLIENTE FROM AGTARMAV02 WHERE CODIGO_CLIENTE NOT IN 
		(SELECT CODIGO_CLIENTE FROM AGTARMAV02 
		WHERE (RCC_SET2014 = 'NORMAL' OR RCC_SET2014 = 'SIN REGISTRO') 
		AND (RCC_SET2014 = 'NORMAL' OR RCC_SET2014 = 'SIN REGISTRO') 
		AND (RCC_SET2014 = 'NORMAL' OR RCC_SET2014 = 'SIN REGISTRO')
		AND (RCC_SET2014 = 'NORMAL' OR RCC_SET2014 = 'SIN REGISTRO')
		AND (RCC_SET2014 = 'NORMAL' OR RCC_SET2014 = 'SIN REGISTRO')
		AND (RCC_SET2014 = 'NORMAL' OR RCC_SET2014 = 'SIN REGISTRO')		
		)
		) AS tmp98

		select CODIGO_CLIENTE from #tmp_roche

		SELECT * FROM AGTARMAV02 WHERE CODIGO_CLIENTE = '107010651555'


	SELECT 
	--Datos del Cliente	
	CLIM.cNroDocIde as 'NroDocumento'
	,CLI.cCodCliente AS 'CODIGO_CLIENTE'
	,CLIM.cNomCliente AS 'NOMBRE_CLIENTE'
	--DATOS DEL CREDITO
	,CRE.cCodCtaCre AS 'CODIGO_CREDITO'
	,EC.cDescriEst AS 'ESTADO_DEL_CREDITO'
	,CRE.dFecDesCre as 'Fecha_Desembolso_Credito'
	,CRE.nMonCapDes as 'MONTO_DESEMBOLSADO' 
	,case CRE.cCodTipMon 
	 When '1' then 'SOLES'
	 WHEN '2' THEN 'DOLARES'
	 END as 'MONEDA'
	,CRE.cCodTipCre
	,STC.cDesTipCre AS 'TIPO_DE_CREDITO'
	,STC.cDesSubTip AS 'SUB_TIPO_DE_PRESTAMO'
	,CRE.cCodProduc
	,STC.cDesProCre AS 'PRODUCTO_CREDITICIO' 
	,CRE.cCodSubPro	
	,STC.cDesSubcRE AS 'SUBPRODUCTO_CREDITICIO'	
	,O.cDesOficin AS 'NOMBRE_AGENCIA'
	,zo.cNomZona as 'Detalle_Zona', zon.cDesZona as 'Zona'
	,CRE.cCodUsuAna AS 'COD_ANALISTA'--COD ANALISTA
	,SP.cNomPerson AS 'NOMBRE_ANALISTA'--NOMBRE ANALISTA  
FROM [HYO00402].SOFCMACHYO_DIARIO_MANIANA.dbo.[KPYMCRECONVEN] CRE (NOLOCK)		
	INNER JOIN [HYO00402].SOFCMACHYO_DIARIO_MANIANA.dbo.[GENMCRECLI] CLI 
			ON CLI.cCodCtaCre = CRE.cCodCtaCre
	INNER JOIN [HYO00402].CMACHYOCLI_MANIANA.dbo.[CLIMCLIENTES] CLIM 
		    ON CLIM.cCodCliente = CLI.cCodCliente
	INNER JOIN [HYO00402].SOFCMACHYO_DIARIO_MANIANA.dbo.[KPYTEstCreCon] EC 
			ON EC.cEstCreCon = CRE.cEstCreCon
	inner JOIN [HYO00402].SOFCMACHYO_DIARIO_MANIANA.dbo.[sipmpersonal] SP 
	        ON SP.cCodPerson = CRE.cCodUsuAna
	INNER JOIN [HYO00402].SOFCMACHYO_DIARIO_MANIANA.dbo.[GENTOficinas] O 
	        ON O.cCodOficin = CRE.cCodOficin
	INNER JOIN [HYO00402].SOFCMACHYO_DIARIO_MANIANA.dbo.[KPYDPRODUCTO] PROD
			ON CRE.cCodProduc =  PROD.cCodProduc and CRE.cCodTipCre = PROD.cCodTipCre
	INNER JOIN [HYO00402].SOFCMACHYO_DIARIO_MANIANA.dbo.[KPYDSUBPRODUC] SPRO
			ON CRE.cCodSubPro = SPRO.cCodSubPro AND CRE.cCodTipCre = SPRO.cCodTipCre
			AND CRE.cCodProduc =  SPRO.cCodProduc
	INNER JOIN [HYO00402].SOFCMACHYO_DIARIO_MANIANA.dbo.[KPYTSUBTIPCRE] STC
			ON CRE.cCodTipCre = STC.cCodTipCre AND CRE.cCodProduc = STC.cCodProduc 
			AND CRE.cCodSubPro = STC.cCodSubPro and STC.lEstado = '1'
	INNER JOIN [HYO00402].SOFCMACHYO_DIARIO_MANIANA.dbo.[GentZona] zo
		ON ZO.cCodZona = O.cCodZona and zo.cCodDepart = O.cCodDepart
		and zo.cCodProvin = O.cCodProvin  and zo.cCodDistri = O.cCodDistri
	INNER JOIN [HYO00402].SOFCMACHYO_DIARIO_MANIANA.dbo.[Gentofizonas] goz
		ON goz.cCodOficin = O.cCodOficin
	INNER JOIN  [HYO00402].SOFCMACHYO_DIARIO_MANIANA.dbo.[GentZonas] zon
		ON goz.nCodZona = zon.nCodZona	
WHERE CLI.cCodCliente  COLLATE SQL_Latin1_General_CP1_CI_AS	
		--IN (select CODIGO_CLIENTE from AGTARMAV02 ) -- 
		--in (SELECT CODIGO_CLIENTE FROM #tmp_normal)
		IN (select CODIGO_CLIENTE from #tmp_roche)
		AND CRE.cEstCreCon = 'F'
		and CRE.cCodOficin = '003'
*/