
SELECT * 
FROM HYO00410.URIESGOS.dbo.[#TMPCLICAJA]

SELECT TOP 5 * 
FROM HYO00410.URIESGOS.dbo.[URIRCCMAE808] A (NOLOCK)
--SELECT * FROM #TMPCLICAJA -- (165282 row(s) affected)
--DROP TABLE #TMPCLICAJA

--CREATE NONCLUSTERED INDEX #TMPCLI_cCodcliente_IXN ON #TMPCLI(cCodCliente)

--INDEXANDO
		--CREATE NONCLUSTERED INDEX #TMPCLICAJA_CodSBS_IXN ON #TMPCLICAJA(CodSBS)
