--/////////////////////////////////////////////////////////////////
-- CLIENTES QUE SON REPORTADOS POR LA CAJA
--SELECT DISTINCT CCODSBS INTO #TMPCLIHYO
--FROM URIESGOS.dbo.URIRCCSAL808
--WHERE CCODEMP = '00107'

--CREATE NONCLUSTERED INDEX #TMPCLIHYO_cCodSbs ON #TMPCLIHYO(cCodSbs)
--USE URIESGOS
--Extrae todos los saldos de los clientes de la caja y otras ifis
DECLARE @DETCTA TABLE
       (ccodcta CHAR(4)COLLATE SQL_Latin1_General_CP1_CI_AS PRIMARY KEY)

--No incluye créditos indirectos, ni castigados
INSERT INTO @detcta
       VALUES
       ('1411'), --Credito Microempresa Soles
       ('1413'), --Credito Reestructurado Soles
       ('1414'), --Creditos Refinanciados Soles
       ('1415'), --Creditos Vencidos Soles
       ('1416'), --Cred Cobranza Judicial Soles
       ('1421'), --Credito Microempresa Dolares
       ('1423'), --Credito Reestructurado Dolares
       ('1424'), --Creditos Refinanciados Dolares
       ('1425'), --Creditos Vencidos Dolares
       ('1426')  --Cred Cobranza Judicial Dolares
	   
-- SOLO VIGENTES EN CMAC HYO
SELECT DISTINCT A.CCODSBS INTO #TMPCLIHYO
FROM URIESGOS.dbo.URIRCCSAL808 A
INNER JOIN @detcta C ON LEFT(A.Cctacon, 4) = C.ccodcta COLLATE SQL_Latin1_General_CP1_CI_AS
WHERE CCODEMP = '00107'

CREATE NONCLUSTERED INDEX #TMPCLIHYO_cCodSbs ON #TMPCLIHYO(cCodSbs)

SELECT A.CCODSBS, A.CCODEMP, A.CTIPCRE,
       SUM(A.NSALDOS) AS NSALDOS
  INTO #TMPRCC
  FROM URIESGOS.dbo.URIRCCSAL808 A
  INNER JOIN #TMPCLIHYO B ON A.CCODSBS = B.CCODSBS
  INNER JOIN @detcta C ON LEFT(A.Cctacon, 4) = C.ccodcta COLLATE SQL_Latin1_General_CP1_CI_AS
  GROUP BY A.CCODSBS, A.CCODEMP, A.CTIPCRE

--Clientes de otras instituciones
SELECT CCODSBS, CTIPCRE
INTO #TMPCLIOTRAS01
FROM #TMPRCC
WHERE RTRIM(CCODEMP) != '00107'
ORDER BY CCODSBS, CTIPCRE

--Clientes CMACHYO
SELECT DISTINCT CCODSBS, CTIPCRE
INTO #TMPCLICMAC
FROM #TMPRCC
WHERE CCODSBS NOT IN (SELECT DISTINCT CCODSBS FROM #TMPCLIOTRAS01)
ORDER BY CCODSBS

--Clientes otras ifis y la caja, que no son exclusivos
SELECT DISTINCT CCODSBS, CTIPCRE
INTO #TMPCLIOTRAS
FROM #TMPRCC
WHERE CCODSBS NOT IN (SELECT DISTINCT CCODSBS FROM #TMPCLICMAC)
ORDER BY CCODSBS

--Clientes compartidos
SELECT DISTINCT CCODSBS, CTIPCRE, CCODEMP
INTO #TMPCLICOMP
FROM #TMPRCC
WHERE CCODSBS NOT IN (SELECT DISTINCT CCODSBS FROM #TMPCLICMAC)
ORDER BY CCODSBS

--Total clientes
SELECT DISTINCT CCODSBS, CTIPCRE
INTO #TMPCLITOT
FROM #TMPRCC ORDER BY CCODSBS, CTIPCRE

--Numero de clientes exclusivos
SELECT CTIPCRE, COUNT(*) AS nCliExclu
INTO #TMPCLICMAC1
FROM #TMPCLICMAC
GROUP BY CTIPCRE ORDER BY CTIPCRE

--Numero de clientes compartidos
SELECT CTIPCRE, COUNT(*) AS nCliComp
INTO #TMPCLIOTRAS1
FROM #TMPCLIOTRAS
GROUP BY CTIPCRE ORDER BY CTIPCRE

--Total clientes
SELECT CTIPCRE, COUNT(*) AS TOTCLI
INTO #TMPCLITOT1
FROM #TMPCLITOT
GROUP BY CTIPCRE ORDER BY CTIPCRE

--Determinando total de clientes compartidos

SELECT CTIPCRE, CCODSBS, COUNT(*) AS NUM
INTO #TMP03
FROM #TMPRCC --#TMPCLICOMP
GROUP BY CTIPCRE, CCODSBS
ORDER BY CCODSBS, CTIPCRE

SELECT CCODSBS, SUM(NUM) AS TOTAL
  INTO #TMP04
  FROM #TMP03
  GROUP BY CCODSBS
  ORDER BY CCODSBS

SELECT A.CTIPCRE, A.CCODSBS, B.TOTAL AS NUM
INTO #TMP06
FROM #TMP03 A INNER JOIN #TMP04 B 
ON A.CCODSBS = B.CCODSBS
--WHERE B.TOTAL = 1

SELECT CTIPCRE, SUM(CASE WHEN NUM = 1 THEN NUM ELSE 0 END) AS UNO,
                SUM(CASE WHEN NUM = 2 THEN NUM ELSE 0 END) AS DOS,
                SUM(CASE WHEN NUM = 3 THEN NUM ELSE 0 END) AS TRES,
                SUM(CASE WHEN NUM = 4 THEN NUM ELSE 0 END) AS CUATRO,
                SUM(CASE WHEN NUM >= 5 THEN NUM ELSE 0 END) AS MAS
INTO #TMPF
FROM #TMP06
GROUP BY CTIPCRE
ORDER BY CTIPCRE

--Uniendo reporte
SELECT A.cCodCreSBS AS CODCRE, A.cDesTipCre AS TIPCRE,
       ISNULL(B.TOTCLI, 0) AS TOTALCLI, ISNULL(C.nCliExclu, 0) AS CLI_EXCLU,
       ISNULL(D.nCliComp, 0) AS CLI_COMP
INTO #TMPFF
FROM URIESGOS.dbo.URITTipCredit A
  LEFT JOIN #TMPCLITOT1 B ON A.cCodCreSbs = B.CTIPCRE
  LEFT JOIN #TMPCLICMAC1 C ON A.cCodCreSbs = C.CTIPCRE
  LEFT JOIN #TMPCLIOTRAS1 D ON A.cCodCreSbs = D.CTIPCRE
ORDER BY A.cCodCreSBS

--UNE RESULTADOS
SELECT A.*, ISNULL(B.UNO, 0) AS UNO,
       ISNULL(B.DOS, 0) AS DOS,
       ISNULL(B.TRES, 0) AS TRES,
       ISNULL(B.CUATRO, 0) AS CUATRO,
       ISNULL(B.MAS, 0) AS MAS
  FROM #TMPFF A LEFT JOIN #TMPF B ON A.CODCRE = B.CTIPCRE

--Elimina tablas temporales
DROP TABLE #TMPCLIOTRAS
DROP TABLE #TMPCLICMAC
DROP TABLE #TMPCLITOT
DROP TABLE #TMPRCC
DROP TABLE #TMPCLIHYO
DROP TABLE #TMPCLIOTRAS01

DROP TABLE #TMPCLITOT1
DROP TABLE #TMPCLICMAC1
DROP TABLE #TMPCLIOTRAS1
DROP TABLE #TMPCLICOMP
DROP TABLE #TMP03
DROP TABLE #TMP04
DROP TABLE #TMP06

DROP TABLE #TMPF
DROP TABLE #TMPFF
